GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
// this is kinda getting non-vcs-friendly
GET http://localhost:3001/api/persons/643c0a93f7e60d41fb95fa89

###
DELETE http://localhost:3001/api/persons/643c0a93f7e60d41fb95fa89

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Joshua Meyers",
    "number": "34-23-222345"
}
###
// duplicate test
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "040-123456"
}